version: '2'
services:
  egg:
    build:
      context: egg-backend
      dockerfile: Dockerfile.deploy
    volumes:
      - ./egg-backend/app/public/:/usr/src/app/app/public/
    depends_on:
      - db
    ports:
      - "7001:7001"
  db:
    image: mysql:5.7
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=newpass
      - FOREIGN_KEY_CHECKS=0
      - MYSQL_DATABASE=world
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf